- job:
    name: zunclient-devstack-docker-sql
    parent: legacy-dsvm-base
    run: playbooks/zunclient-devstack-docker-sql/run.yaml
    post-run: playbooks/zunclient-devstack-docker-sql/post.yaml
    timeout: 4200
    required-projects:
      - openstack-dev/devstack
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-container
      - openstack/kuryr-libnetwork
      - openstack/python-zunclient
      - openstack/zun
      - openstack/zun-tempest-plugin

- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
      - check-requirements
      - publish-openstack-docs-pti
    check:
      jobs:
        - zunclient-devstack-docker-sql
    gate:
      jobs:
        - zunclient-devstack-docker-sql
