- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
      - check-requirements
      - publish-openstack-docs-pti
    check:
      jobs:
        - zunclient-devstack-docker-sql:
            voting: false
